name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          project_name: test-project
          waiting_column_name: In waiting
          to_column_name: To do
          prefix_for_datetime: waiting till DATETIME/
          labels_to_ignore: '["will close automatically by PR", "will do at convenience store"]'
          number_of_days_to_ignore_label: 14
          github_token: ${{ secrets.GH_TOKEN }}
